<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\Forms\Events\" />
    <Folder Include="Entities\Functions\Events\" />
    <Folder Include="Entities\Permissions\Enums\" />
    <Folder Include="Entities\Permissions\Events\" />
    <Folder Include="Entities\RequestLogs\Enums\" />
    <Folder Include="Entities\RequestLogs\Events\" />
    <Folder Include="Entities\WorkFlowSteps\Events\" />
    <Folder Include="Entities\WorkFlowStepTransitions\Events\" />
  </ItemGroup>

</Project>
